web/dashboard/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('myapp/', include("myapp.urls")),
    path('admin/', admin.site.urls),
    path('', include("myapp.urls"))
]

web/myapp/urls.py
from django.urls import path
from . import views
from .views import LoginClass, RegisterClass

app_name = "myapp"

urlpatterns = [
    path('', views.index, name="index"),
    path('dashboard/', views.dashBoardView, name="dashboard"),
    path('pushHumi/', views.pushHumi, name="pushHumi"),
    path('initHumi/', views.initHumi, name="trang2"),
    path("initWeek/", views.initDataWeek, name="initWeek"),
    path('trang3', views.getNewestData, name="getNewestData"),
    path('login/', LoginClass.as_view(), name="login"),
    path('register/', RegisterClass.as_view(), name="register"),
    path('logout/', views.logoutUser, name="logout"),
    path('pushData/', views.pushData, name="pushData"),
    path('statistical_data/', views.statistical_data, name="staticaldata"),
]

web/myapp/models.py
from django.db import models
# from django.db.models.functions import 

# Create your models here


class Humis(models.Model):
    humi = models.IntegerField()
    time = models.DateTimeField()
    
class Temp(models.Model):
    temp = models.IntegerField()
    time = models.DateTimeField()
    
class BadCar(models.Model):
    badcar = models.IntegerField()
    time = models.DateTimeField()

web/myapp/forms.py
from dataclasses import field
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class ResgisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

web/myapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, JsonResponse
from .models import Humis, Temp, BadCar
from .forms import ResgisterForm
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db.models.functions import ExtractWeek, ExtractYear, ExtractMonth
from django.db.models import Avg, Sum
from django.contrib import messages
from Adafruit_IO import Client
import json
import datetime

# @login_required(login_url='myapp:login')
def pushControl(data):
    aio = Client('khanhtran01', 'aio_aVYg97AKI9fGh3lqSa9lShUqm48Z')
    feed = aio.feeds('control')
    res = ''
    if data == 'emer':
        res = '{"emer":"1","slow":"0"}'
    else: res = '{"emer":"0","slow":"1"}'
    aio.send_data(feed.key, res)

def pushTime(data):
    # {"changed":"0","valueTime":"[23,5,25,3]"}
    aio = Client('khanhtran01', 'aio_aVYg97AKI9fGh3lqSa9lShUqm48Z')
    if 'yellow' in data:
        feed = aio.feeds('time')
        res = '{"changed":"'+ str(data['action']) +  '","valueTime":[' + str(data['green']) + ',' + str(data['yellow']) + ',' + str(data['green2']) + ',' + str(data['yellow2']) +  ']}'
    else :
        feed = aio.feeds('control')
        res = '{"emer":"'+ str(data['emer']) +'","slow":"'+ str(data['slow']) + '"}'
    aio.send_data(feed.key, res)

def pushStatic(data):
    # {"changed":"0","valueTime":"[23,5,25,3]"}
    aio = Client('khanhtran01', 'aio_aVYg97AKI9fGh3lqSa9lShUqm48Z')
    feed = aio.feeds('statical')
    res = json.dumps(data)
    aio.send_data(feed.key, res)
    

def is_ajax(request):
    return request.META.get('HTTP_X_REQUESTED_WITH') == 'XMLHttpRequest'
# @login_required(login_url='myapp:login')
def index(request):
    return render(request, "myapp/userBoard.html")

@login_required(login_url='myapp:login')
def pushHumi(request):
    if request.method == "POST":
        # humiInput = Humis(humi = int(request.POST['humi']), time= datetime.datetime.now()) 
        # humiInput.save()
        return JsonResponse({'data': "here is new data", 'message' : "input complete"}, status=200)
    else:
        return JsonResponse({'data': "here is new data", 'message' : "failed"}, status=200)
    
# @login_required(login_url='myapp:login')
# def detailsView(request, idx):
#     q = Question.objects.get(pk=idx)
#     res = {
#         'details': q
#     }
#     return render(request, "myapp/detail.html", res)


@login_required(login_url='myapp:login')
def dashBoardView(request):
    if request.method == "POST":
        pushControl(request.POST['Setlight'])
        return render(request, "myapp/dashboard.html")
        
    
    return render(request, "myapp/dashboard.html")
def statistical_data(request):
    temp = Temp.objects.all().order_by('-temp')[:1]
    cars = (BadCar.objects
                .annotate(month = ExtractMonth('time'))
                .values('month')
                .annotate(total=Sum('badcar')))
    highest = cars.order_by('-total')[:1]
    total = BadCar.objects.aggregate(Sum('badcar'))
    des = {
        'temp' : temp[0].temp,
        'time' : temp[0].time,
        'carmonth' : highest[0]['month'],
        'totalcar' : highest[0]['total'],
        'totalcar2' : total['badcar__sum']
    }
    return JsonResponse(des, status=200)


def initDataWeek(request):
    Humidata = (Humis.objects
                .annotate(week = ExtractWeek('time'))
                .values('week')
                .annotate(avg_humi=Avg('humi')))
    Tempdata = (Temp.objects
                .annotate(week = ExtractWeek('time'))
                .values('week')
                .annotate(avg_temp=Avg('temp')))
    HumidataMonth = (Humis.objects
                .annotate(month = ExtractMonth('time'))
                .values('month')
                .annotate(avg_humi=Avg('humi')))
    TempdataMonth = (Temp.objects
                .annotate(month = ExtractMonth('time'))
                .values('month')
                .annotate(avg_temp=Avg('temp')))
    
    BadcarWeek = (BadCar.objects
                .annotate(week = ExtractWeek('time'))
                .values('week')
                .annotate(avg=Avg('badcar')))
    BadcarMonth = (BadCar.objects
                .annotate(month = ExtractMonth('time'))
                .values('month')
                .annotate(avg=Avg('badcar')))
    # Humidata.
    week = []
    humi = []
    humimonthdata = []
    hummimonth = []
    
    badcarmd = []
    badcarw = []
    badcarwd = []
    badcarm = []
    
    tempw = []
    temp = []
    tempmonth = []
    tempmonthdata = []
    
    for i in Humidata:
        week += [i['week']]
        humi += [i['avg_humi']]
    
    for i in Tempdata:
        tempw += [i['week']]
        temp += [i['avg_temp']]
    
    for i in HumidataMonth:
        hummimonth += [i['month']]
        humimonthdata += [i['avg_humi']]
    
    for i in TempdataMonth:
        tempmonth += [i['month']]
        tempmonthdata += [i['avg_temp']]
        
    for i in BadcarWeek:
        badcarw += [i['week']]
        badcarwd += [i['avg']]
        
    for i in BadcarMonth:
        badcarm += [i['month']]
        badcarmd += [i['avg']]
    
    res = {
        'humiweek' : week,
        'humi' : humi,
        'tempweek' : tempw,
        'temp' : temp,
        'humimonth' : hummimonth,
        'humimonthdata' : humimonthdata,
        'tempmonth' : tempmonth,
        'tempmonthdata' : tempmonthdata,
        'badcarweek' : badcarw,
        'badcarweekdata' : badcarwd,
        'badcarmonth' : badcarm,
        'badcarmonthdata' : badcarmd
    }
    return JsonResponse(res, status= 200)

# @login_required(login_url='myapp:login')
def initHumi(request):
    humis = Humis.objects.all().order_by('-id')[:20:-1]
    temps = Temp.objects.all().order_by('-id')[:20:-1]
    badcars = BadCar.objects.all().order_by('-id')[:20:-1]
    humilist = []
    humitime = []
    templist = []
    temptime = []
    badcarlist = []
    badcartime = []
    for humi in humis:
        humilist += [humi.humi]
        humitime += [humi.time]
    for temp in temps:
        templist += [temp.temp]
        temptime += [temp.time]
    for car in badcars:
        badcarlist += [car.badcar]
        badcartime += [car.time]
    
    resu = {
        'humidata' : humilist,
        'humitime' : humitime,
        'tempdata' : templist,
        'temptime' : temptime,
        'cardata' : badcarlist,
        'cartime' : badcartime
    }
    return JsonResponse(resu, status= 200)


@login_required(login_url='myapp:login')
def getNewestData(request):
    q = Humis.objects.all().order_by('-id')[:1]
    resu = {
        'data' : q[0].humi,
        'time' : q[0].time
    }
    return JsonResponse(resu, status= 200)
class LoginClass(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('myapp:dashboard')
        return render(request, "myapp/login.htm")
    
    def post(self, request):
        username = request.POST.get('username')
        password = request.POST.get('password')
        my_user = authenticate(request ,username = username, password = password)
        
        if my_user is not None:
            login(request, my_user)
            return redirect('myapp:dashboard')
        else:
            messages.info(request, 'Tên người dùng hoặc mật khẩu không đúng')
        
        return render(request, 'myapp/login.htm')
class RegisterClass(View):
    def get(self,request):
        if request.user.is_authenticated:
            return redirect('myapp:index')
        form = ResgisterForm()
        context = {'forms': form}
        return render(request, "myapp/register.htm", context)
    
    def post(self,request):
        form = ResgisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('myapp:login')
        context = {'forms': form}
        return render(request, "myapp/register.htm", context)
    
    
def logoutUser(request):
    logout(request)
    return redirect('myapp:login')

# @login_required(login_url='myapp:login')
def pushData(request):
    if request.method == "POST":
        if 'yellow_time' in request.POST:            
            yellow = request.POST['yellow_time']
            green = request.POST['green_time']
            yellow2 = request.POST['yellow_time2']
            green2 = request.POST['green_time2']
            action = request.POST['action']
            if (int(yellow) + int(green)) != (int(yellow2) + int(green2)):
                return JsonResponse({'status':False}, status=200)
            res = {
                'yellow' : yellow,
                'green' : green,
                'yellow2' : yellow2,
                'green2' : green2,
                'action' : action
            }
            pushTime(res)
            if action == '0':
                message = {
                    'status' : True,
                    'time' : int(yellow2) + int(green2)
                }
            else:
                message = {
                    'status' : True,
                }
            return JsonResponse(message, status=200)
        elif 'Setlight' in request.POST:
            res = {
                'emer' : 0,
                'slow' : 1
            }
            if request.POST['Setlight'] == 'emer':
                res = {
                    'emer' : 1,
                    'slow' : 0
                }
            elif request.POST['Setlight'] == 'normal':
                res = {
                    'emer' : 0,
                    'slow' : 0
                }
            pushTime(res)
            return JsonResponse({'status': "complete", 'message' : "success"}, status=200)
    elif request.method == "GET":
        if 'car' in request.GET:
            car = BadCar(badcar = int(request.GET['car']), time = datetime.datetime.now())
            car.save()
            return JsonResponse({'status': "complete", 'message' : "push car"}, status=200)

web/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <style>
        body {
            background-color: #555;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>
        this is header line
        </h1>

    </div>
    <div id="div1"></div>
    <div class="content">
        {% block something %}
        {% endblock %}
    </div>
    {% comment %} <input data-url="{% url 'myapp:index' %}" type="submit" id="btn" class="btn"></input> {% endcomment %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{% static 'myapp/js/ajax_base.js' %}"></script>
</body>
</html>

web/myapp/templates/myapp/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <meta charset="UTF-8">
    <link href="https://fonts.googleapis.com/css2?family=My+Soul&family=Nunito:wght@300&family=Roboto&display=swap" rel="stylesheet">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'myapp/themify-icons/themify-icons.css' %}">
    <link rel="stylesheet" href="{% static 'myapp/fontawesome-free-6.1.1-web/css/all.css' %}">
    <title>DashBoard</title>
</head>

<body>
    <div class="screencover">
        <div id="trafficLightModal">
            <div id="Modal">
                <p class="Modal--title">
                    Điều khiển đèn giao thông
                </p>
                <div class="close_icon" onclick="closeModal()">
                    <em class="fa-solid fa-xmark"></em>
                </div>
                <form class="Traffic_time_form" action="{% url 'myapp:pushData' %}" method="post">
                    {% csrf_token %}
                    
                    <label for="green_time">Đèn xanh 1</label>
                    <input type="number" name="green_time" id="green_time">
                    <label for="yellow_time">Đèn vàng 1</label>
                    <input type="number" name="yellow_time" id="yellow_time">
                    <label for="green_time2">Đèn xanh 2</label>
                    <input type="number" name="green_time2" id="green_time2">
                    <label for="yellow_time2">Đèn vàng 2</label>
                    <input type="number" name="yellow_time2" id="yellow_time2">
                    <div class="save_and_confirm">
                        <input id="settimesubmit" name="action" type="submit" value="Save">
                        <input onclick="closeModal()"name="action" id="comfirm_time" type="submit" value="Update">
                    </div>
                </form>
            </div>
        </div>
        <div id="mapModal">
            <div id="map">
                <div class="closemap" onclick="closeMap()">
                    <em class="fa-solid fa-xmark"></em>
                </div>
                <img src="{% static 'myapp/img/map.png' %}" alt="map">
            </div>
        </div>

        <div id="settrafficLightModal">
            <div id="setModal">
                <p class="Modal--title">
                    Điều khiển đèn giao thông
                </p>
                <div class="setclose_icon" onclick="closeSetModal()">
                    <em class="fa-solid fa-xmark"></em>
                </div>
                <form class="setTraffic_time_form" action="{% url 'myapp:pushData' %}" method="post">
                    {% csrf_token %}
                    <div class="radio-setlight">
                        <input type="radio" id="red" name="Setlight" value="emer">
                        <label for="red">Đỏ</label>
                    </div>
                    <div class="radio-setlight">
                        <input type="radio" id="yellow" name="Setlight" value="slow">
                        <label for="yellow">Vàng</label>
                    </div>
                    <div class="radio-setlight">
                        <input type="radio" id="normal" name="Setlight" value="normal">
                        <label for="normal">Bình thường</label>
                    </div>
                    <input onclick="closeSetModal()" type="submit" value="Chỉnh sửa">
                </form>
            </div>
        </div>


        <div class="leftside" id="leftside">
            <div class="leftheader">
                <p id="groupName">
                    Super Idol
                </p>
            </div>
            <div class="leftcontainer">
                <div class="menubox">
                    <div class="menutitle">
                        <span>Điều khiển</span>
                    </div>
                    <div class="listmenuchoose">
                        <div class="normalselection">
                            <div onclick="openModal()" class="leftsideselection">
                                <em class="fa-solid fa-traffic-light"></em>
                                <div class="menutext">
                                    <span>Thời gian đèn giao thông</span>
                                </div>
                            </div>

                        </div>
                        <div class="normalselection" onclick="openSetModal()">
                            <div class="leftsideselection">
                                <em class="fa-solid fa-screwdriver-wrench"></em>
                                <div class="menutext">
                                    <span>Điều khiển đèn</span>    
                                </div>
                            </div>

                        </div>

                    </div>
                </div>

                <div class="menubox">
                    <div class="menutitle">
                        <span>Tính năng</span>
                    </div>
                    <div class="listmenuchoose">
                        <div class="normalselection" onclick="openMap()">
                            <div class="leftsideselection">
                                <em class="fa-solid fa-map"></em>
                                <div class="menutext" >
                                    <span>Bản đồ</span>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>





        <div class="rightside" id="rightside">
            <div class="rightheader">
                <div class="navbar">
                    <div class="leftnav">
                        <div id="menubtn" class="menuicon" onclick="changestatus()">
                            <em class="ti-menu-alt"></em>
                        </div>

                        <div class="dropdownbtn">
                            <div class="positionname">
                                <span class="text">Ngã tư hàng xanh</span>
                                <em class="ti-angle-down"></em>
                            </div>
                            <div class="dropdownContent">
                                <a href="">Ngã 3 Chương Dương</a>
                                <a href="">Đường Điện Biên Phủ</a>
                                <a href="">Công viên Hoàng Văn Thụ</a>
                            </div>
                        </div>
                    </div>
                    <div class="rightnav">
                        <div class="userinfo">

                            <p>Xin chào, <b>{{ request.user }}</b></p>
                        </div>
                        <a class="logout" href="{% url 'myapp:logout' %}">Thoát</a>
                    </div>
                </div>
            </div>
            <div class="rightcontainer">
                <div class="tagsList">
                    <a onclick="tabsto(0)" id="day">Theo ngày</a>
                    <a onclick="tabsto(1)" id="week">Theo tuần</a>
                    <a onclick="tabsto(2)" id="month">Theo tháng</a>
                </div>
                <div class="listreport">
                    <div class="infomation redcolor">
                        <p>Thời điểm có nhiệt độ cao nhất : </p>
                        <p id="report1"></p>
                    </div>
                    <div class="infomation redcolor">
                        <p>Tháng có số xe vượt đèn đỏ nhiều nhất :</p>
                        <p id="report2"></p>
                    </div>
                    <div class="infomation redcolor">
                        <p>Tổng số xe vượt đèn đỏ được ghi nhận :</p>
                        <p id="report3"></p>
                    </div>
                    <!-- <div class="infomation bluecolor">
                        <span>Ngày có lượng xe vượt ngưỡng cao nhất : 14/02/2022</span>
                    </div>

                    <div class="infomation greencolor">
                        <span>Ngày có lượng xe vượt ngưỡng cao nhất : 14/02/2022</span>
                    </div> -->
                </div>
                <div class="boards">
                    <div class="board activate">
                        <p class="board_title">
                            Biểu đồ theo ngày
                        </p>
                        <div class="chart">
                            <canvas class="board-element" id="humiChart"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                            <!-- <canvas id="myChart1" style="width:100%;max-width:600px;height:300px"></canvas> -->
                            <canvas class="board-element" id="tempChart"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                        </div>
                        <div class="chart">
                            <canvas class="board-element" id="badCarChart"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                        </div>
                    </div>


                    <div class="board">
                        <p class="board_title">
                            Biểu đồ theo tuần
                        </p>
                        <div class="chart">
                            <canvas class="board-element" id="humiChart_week"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                            <!-- <canvas id="myChart1" style="width:100%;max-width:600px;height:300px"></canvas> -->
                            <canvas class="board-element" id="tempChart_week"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                        </div>
                        <div class="chart">
                            <canvas class="board-element" id="badCarChart_week"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                        </div>
                    </div>
                    
                    <div class="board">
                        <p class="board_title">
                            Biểu đồ theo tháng
                        </p>
                        <div class="chart">
                            <canvas class="board-element" id="humiChart_month"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                            <!-- <canvas id="myChart1" style="width:100%;max-width:600px;height:300px"></canvas> -->
                            <canvas class="board-element" id="tempChart_month"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                        </div>
                        <div class="chart">
                            <canvas class="board-element" id="badCarChart_month"
                                style="width:100%;max-width:500px; height: 300px"></canvas>
                        </div>
                    </div>
                    
                </div>
                

            </div>
            <div class="rightfooter">
                <p id="demo"></p>
            </div>
        </div>
    </div>
    <script src="{% static 'myapp/js/animation.js' %}"></script>
    <script src="{% static 'myapp/js/chart.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="{% static 'myapp/js/liveChart.js' %}"></script>
    <script src="{% static 'myapp/js/tabs.js' %}"></script>
    <script src="{% static 'myapp/js/pushdata.js' %}"></script>

</body>

</html>

web/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}
    {% block something %}
    <h1>This is details view</h1>

    <p> : {{ details.ques }} : </p>
<!--    <ul>-->
<!--        {% for item in items %}-->
<!--        <li>bao gom : {{item.something}}</li>-->
<!--        {% endfor %}-->
<!--    </ul>-->
    <a href="{% url 'myapp:index' %}">Back</a>
    {% endblock %}

web/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
    {% block something %}
    <h1>Hè lố ô {{ request.user }}</h1>

    <ul>
        {% for item in items %}
        <li> <a href="{% url 'myapp:details' item.id %}">bao gom : {{item.something}}</a></li>
        {% endfor %}
    </ul>
    <form id="form_id" action="{% url 'myapp:pushHumi' %}" method="post">
        {% csrf_token %}
        <input id="input_id" type="text" name="humi">
        <input type="submit">
    </form>
    <p><a href="{% url 'myapp:dashboard' %}">go to dashboard</a></p>
    <p><a href="{% url 'myapp:logout' %}">logout</a></p>
    {% endblock %}

web/myapp/templates/myapp/login.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href=" {% static 'myapp/css/login.css' %} ">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&family=Roboto&display=swap" rel="stylesheet">
    <title>Đăng nhập</title>
</head>
<body>
    <div class="form">
        <p id="title">Đăng nhập</p>
        <form action="" method="post">
            {% csrf_token %}
            <label class="subtitle" for="">Username</label><br>
            <input type="text" name="username" id="" placeholder="Nhập username của bạn tại đây"><br>
            <label class="subtitle" for="password">Password</label><br>
            <input type="password" name="password" placeholder="Nhập mật khẩu" >
            {% for message in messages %}
                <p class="error-message">{{ message }}</p>
            {% endfor %}
            <div class="sub">
                <div class="register-require">
                    <p>Bạn chưa có tài khoản?</p>
                    <a href="{% url 'myapp:register' %}">Đăng ký</a>
                </div>
                <button type="submit">Đăng nhập</button>
            </div>
        </form>
    </div>
</body>
</html>

web/myapp/templates/myapp/register.htm
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'myapp/css/login.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300&family=Roboto&display=swap" rel="stylesheet">
    <title>Đăng ký</title>
</head>
<body>
    <div class="form">
        <p id="title">Đăng ký</p>
        <form action="" method="post">
            {% csrf_token %}

            <label class="subtitle" for="">Username</label><br>
            {{forms.username}}
            {% comment %} <input type="text" name="" id="" placeholder="Nhập username của bạn tại đây"><br> {% endcomment %}
            <label class="subtitle" for="">Email</label><br>
            {{forms.email}}
            {% comment %} <input type="email" name="" id="" placeholder="Nhập email của bạn tại đây"><br> {% endcomment %}
            <label class="subtitle" for="password">Mật khẩu</label><br>
            {{forms.password1}}
            {% comment %} <input type="text" placeholder="Nhập mật khẩu"> {% endcomment %}
            <label class="subtitle" for="password">Nhập lại mật khẩu</label><br>
            {{forms.password2}}
            {% comment %} <input type="text" placeholder="Nhập lại mật khẩu"> {% endcomment %}
            <div class="sub">
                <div class="register-require">
                    <p>Bạn đã có tài khoản?</p>
                    <a href="{% url 'myapp:login' %}">Đăng nhập</a>
                </div>
                <button type="submit">Đăng Ký</button>
            </div>
            {{ forms.errors }}
        </form>
    </div>
</body>
</html>

web/myapp/templates/myapp/trang2.html
{% extends 'myapp/base.html' %}
    {% block something %}
    <h1>This is details view</h1>
    {% for item in data %}
        <p> : {{ item }} : </p>
    {% endfor %}
    <a href="{% url 'myapp:index' %}">Back</a>
    {% endblock %}